version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 3qoLxoCRw7
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
volumes:
  sql-server-data:
